on:
  push:
    branches:
      - main 
      - master
jobs:
  sync_workflows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout This Repo
      uses: actions/checkout@v2
      with:
        path: main
    - name: Check if diff
      run: |
        git diff --exit-code HEAD~ cat.cwl
    - name: Return previous exit code
      if: success()
      run: echo "exit code was $?"
#    - name: Cavatica Push Cat
#      uses: docker://dmiller15/sbpack:20211007
#      env: 
#        SB_AUTH_TOKEN: ${{ secrets.CAVATICA_AUTH_TOKEN }} 
#        SB_API_ENDPOINT: https://cavatica-api.sbgenomics.com/v2
#      with:
#        entrypoint: >
#          git diff --exit-code HEAD..HEAD^ cat.cwl
#          && if [ $? -eq 1 ]; then sbpack . kfdrc-harmonization/kf-reference-pipeline/cat cat.cwl; else echo 'no changes will not push'; fi
